language: php
php: 5.6 # EOL version but can't refactor the code just now
sudo: false
install:
  - composer install
before_install:
  - composer self-update --rollback
  - phpenv config-rm xdebug.ini
script:
  # Updates contents of satis.json
  - php bin/wp-org-api
  # Builds new site based on satis.json
  - php bin/satis build satis.json _site
cache:
  directories:
  - "$HOME/.composer/cache"
env:
  global:
    - GIT_COMMIT_EMAIL: wp-language-bot@keksi.io
    - GIT_COMMIT_USER: WP-Languages bot
    # Deploy into this branch
    - TRAVIS_DEPLOY_BRANCH: master
    - secure: gCrlCqnotIUvDpvVE1B55G1XI1kGdJhdaklVu4Rd6KwSbyK/BQBbOOL/QOu0lTxZKtQM0KVtcDCBFfaROLtat+/NQiUKEX+GoaqbErRucVbWvlrYqIY3P3HuUG20nLyBQ9Ake6ts3ORtOMQ1hbZAu9Ifzj6ll0A+D9obBztqsuS3p4ogDOU+aqTT+nMDzMtpTnWVhf2rHHns3wQNGXh8yJDdFtwbTbXVceNMsskgqbYOsu9za6yCdLxeqnIv68QO9yP+d+Ws5gcVuGk2YCqz28LNOVsMWHecaWBaWxgFvUIBZ+iGvoyloGjk1s4YWv3Y0eb2SEWEFidSHyeNA0uNVgPezqxMly0m9RNaG2Z1VouidWPciE9QObO6ZbzmqKrGkCRbCe5qSNZYWyqowtHLZJvKthV/fCn/yiaj0sIXqQns1HknjD+u34YtAhV71cja9aX1TQAL68ZXYeJd8j6u0nX6BmAiILH8VRzZ13ynx0W9qjjdA/8Iu8cKKpmrX/M1N/tiaWGa05FnkB88L/aoq3rAz3Ir1FR9R0Xa/2MmFVoBGlRjS8tn26MBVB8X3s7fpsOFulXAqGLUx9CEd6IqG/w3pPkdlT/F8Vsi7xzhpiXtiFiNdqhGf50u7O++XVlg6TcgGwFteB4WF+LFWpTNi7Z3iI3IB/9/asDE+nocrAQ=
deploy:
  skip_cleanup: true
  provider: script
  script: bin/travis-deploy-to-gh-pages.sh
  on:
    branch: src
