language: php
php: 7.4
sudo: false
install:
  - composer install
before_install:
  - composer self-update --rollback
  - phpenv config-rm xdebug.ini
script:
  # Updates contents of satis.json
  - php bin/wp-org-api
  # Builds new site based on satis.json
  - php bin/satis build satis.json web
cache:
  directories:
  - "$HOME/.composer/cache"